name: trna_ngs_mod_map_call
owner: rnateam
description: Tool collection for identification of tRNA modifications from NGS data galaxy workflow
homepage_url: 
long_description: 
remote_repository_url: https://github.com/jfallmann/tRNA_ngs_mod_map_call_galaxy.git
type: unrestricted
categories:
- RNA
- NGS
